### ISSUE TITLE
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

### ISSUE THREAD

**Issue by zayKenyon** [therealOri/noter#1]
![image](https://user-images.githubusercontent.com/87788699/141870110-e679b527-85bd-4a04-8e1f-547f2fe0e37c.png)
TOKEN = os.getenv("[TOKEN]")

Python version: 3.9

**Comment by zayKenyon** [comment]
Opened .env with a notepad and figured out to add the bot token there instead, now receiving this error:
![image](https://user-images.githubusercontent.com/87788699/141870625-aa4bd4c4-307f-42fa-81d6-b92bb7978d16.png)

**Comment by therealOri** [comment]
To Solve DiscordAPIError[50001]: Missing Access Error Just Make sure that the 'applications.commands' scope is checked in the scopes section of the OAuth2 settings for your bot in the discord developer portal.

<br />
<br />

![2021-11-15_17-26](https://user-images.githubusercontent.com/45724082/141873788-dea0d195-b860-4b24-bdcb-d15c50928e4e.png)

<br />
<br />

You should get an invite link like the following:
`https://discord.com/api/oauth2/authorize?client_id=<bot_id>&permissions=<permissions_number>&scope=bot%20applications.commands`

<br />
<br />

See if this works for you. You may need to kick and re invite the bot using the new url/link.
Let me know if this works out for you.

**Comment by zayKenyon** [comment]
That solved it, thanks!
